jdbc.database=PostgreSQL
jdbc.database.username=conduit
jdbc.database.password=<password>
jdbc.database.url=jdbc:postgresql://localhost:5432/conduit
jdbc.database.jndi=jdbc/conduit
jdbc.init.sql.schema=/sql/init/schema.sql
jdbc.init.sql.data=/sql/init/data.sql
